import { Dimensions, StyleSheet } from 'react-native';

const screenWidth = Dimensions.get('window').width;
export const lightTheme = StyleSheet.create({
    // HeadBar
    headBar: {
      backgroundColor: 'white',
      padding: 10,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      width: '100%',
      borderBottomWidth: 1,
      borderBottomColor: '#ccc',
      zIndex: 1,
      marginTop: 20,
    },
    headBarText: {
      fontSize: 20,
      fontWeight: 'bold'
    },
    headBarImageContainer: {
      flexDirection: 'row'
    },
    headBarImage: {
      width: 30,
      height: 30,
      marginHorizontal: 5
    },
    // SwipeList
    swipeListContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      overflow: 'visible',
      width: '100%',
    },
    ItemSquareContainer: {
      margin: 1,
      width: screenWidth / 2 - 2,
      flexDirection: 'column',
    },
    ItemSquare: {
      backgroundColor: 'white',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 1,
      borderWidth: 1,
      borderRadius: 5,
      borderColor: '#ccc',
      flex: 1,
    },
    ItemSquareTitleContainer: {
      flexDirection: 'row',
      borderBottomWidth: 1,
      borderBottomColor: '#ccc',
      width: '100%',
    },
    ItemSquareTitle: {
      fontSize: 15,
      fontWeight: 'bold',
      marginLeft: 2,
      textAlign: 'center',
    },
    ItemSquareText: {
      fontSize: 15,
      marginLeft: 2,
      textAlign: 'center',
    },
    ItemSquareDataContainer: {
      flexDirection: 'row',
      margin: 5,
    },
    ItemSquareData: {
      fontSize: 15,
      borderWidth: 1,
      padding: 10,
      margin: 1,
      borderRadius: 5,
      borderColor: '#ccc',
      flexDirection: 'column',
      justifyContent: 'center',
    },
    ItemSquareDataTitle: {
      fontSize: 30,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    ItemSquareDataText: {
      fontSize: 15,
      borderWidth: 1,
      padding: 5,
      borderRadius: 5,
      borderColor: '#ccc',
      textAlign: 'center',
    },
    ItemSquareStatusContainer: {
      flexDirection: 'column',
      width: '100%',
    },
    // SwipeList Hidden Itens
    itemSquareHiddenContainer: {
      flexDirection: 'column',
      flexWrap: 'wrap',
    },
    itemSquareHiddenDetalhes: {
      backgroundColor: 'green',
      padding: 10,
      borderRadius: 5,
      margin: 2,
    },
    itemSquareHiddenDetalhesText: {
      color: 'white',
      fontWeight: 'bold',
    },
    itemSquareHiddenEdit: {
      backgroundColor: 'orange',
      padding: 10,
      borderRadius: 5,
      margin: 2,
    },
    itemSquareHiddenEditText: {
      color: 'white',
      fontWeight: 'bold',
    },
    itemSquareHiddenDelete: {
      backgroundColor: 'red',
      padding: 10,
      borderRadius: 5,
      margin: 2,
    },
    itemSquareHiddenDeleteText: {
      color: 'white',
      fontWeight: 'bold',
    },
    // ConfigBar
    containerConfigBar: {
      position: 'absolute',
      bottom: 0,
      width: '100%',
      backgroundColor: 'white',
      padding: 10,
      borderTopWidth: 1,
      borderTopColor: '#ccc',
    },
    configBarButton: {
      backgroundColor: 'white',
      padding: 10,
      borderRadius: 5,
      borderWidth: 1,
      borderColor: '#ccc',
      margin: 5,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    configBarButtonText: {
      color: 'black',
      fontWeight: 'bold',
      textAlign: 'center',
    },
    configBarImage: {
      width: 20,
      height: 20,
      marginHorizontal: 5,
    },
    configBarTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      textAlign: 'center',
      borderBottomWidth: 1,
      borderBottomColor: '#ccc',
      marginBottom: 10,
    },
    // AddBar
    containerAddBar: {
      position: 'absolute',
      bottom: 0,
      width: '100%',
      backgroundColor: 'white',
      padding: 10,
      borderTopWidth: 1,
      borderTopColor: '#ccc',
    },
    addBarInput: {
      backgroundColor: 'white',
      padding: 10,
      borderRadius: 5,
      borderWidth: 1,
      borderColor: '#ccc',
      margin: 5,
    },
    addBarButton: {
      backgroundColor: 'green',
      padding: 10,
      borderRadius: 5,
      margin: 5,
    },
    addBarButtonText: {
      color: 'white',
      fontWeight: 'bold',
      textAlign: 'center',
    },
    addBarButtonCancelar: {
      backgroundColor: 'red',
      padding: 10,
      borderRadius: 5,
      margin: 5,
    },
    addBarButtonTextCancelar: {
      color: 'white',
      fontWeight: 'bold',
      textAlign: 'center',
    },
    addBarTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      textAlign: 'center',
      borderBottomWidth: 1,
      borderBottomColor: '#ccc',
      marginBottom: 10,
    },
    // DetalhesPage
    detalhesContainer: {
        marginTop: 35,
        width: '100%',
        height: 'auto',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    detalhesContent: {
        backgroundColor: 'white',
        padding: 2,
        borderRadius: 5,
        width: '100%',
    },
    detalhesTitleContainer: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#ccc',
        margin: 5,
        padding: 5,
    },
    detalhesTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    detalhesText: {
        fontSize: 20,
        textAlign: 'center',
        marginLeft: 5,
        marginRight: 5,
    },
    detalhesDataContainer: {
        flexDirection: 'row',
        margin: 2,
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    detalhesData: {
        fontSize: 50,
        borderWidth: 1,
        padding: 30,
        margin: 3,
        borderRadius: 5,
        borderColor: '#ccc',
        flexDirection: 'column',
        justifyContent: 'center',
    },
    detalhesDataTitle: {
        fontSize: 80,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    detalhesDataText: {
        fontSize: 25,
        borderWidth: 1,
        padding: 5,
        borderRadius: 5,
        borderColor: '#ccc',
        textAlign: 'center',
    },
    detalhesStatusContainer: {
        flexDirection: 'column',
        width: '100%',
    },
    detalhesStatus: {
        fontSize: 20, 
        fontWeight: 'bold', 
        textAlign: 'center', 
        padding: 5, 
        borderRadius: 5, 
        borderWidth: 1, 
        borderColor: '#ccc',
        margin: 5,
    },
    detalhesVoltar: { 
        width: 30,
        height: 30,
    },
    detalhesVoltarCotainer: {
        width: '100%',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        padding: 5, 
        borderBottomWidth: 1, 
        borderBottomColor: '#ccc', 
        position: 'absolute',
        top: 0,
        zIndex: 1,
        display: 'flex',
    },
    detalhesButtomExportar: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        margin: 5,
    },
    detalhesButtomExportarCSV: {
        backgroundColor: 'green',
        padding: 10,
        borderRadius: 5,
        margin: 5,
        width: '50%',
    },
    detalhesButtomExportarCSVText: {
        color: 'white',
        fontWeight: 'bold',
        textAlign: 'center',
    },
    detalhesButtomExportarPDF: {
        backgroundColor: 'orange',
        padding: 10,
        borderRadius: 5,
        margin: 5,
        width: '50%',
    },
    detalhesButtomExportarPDFText: {
        color: 'white',
        fontWeight: 'bold',
        textAlign: 'center',
    },
    // Modal
    modalContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)'
    },
    modalContent: {
      backgroundColor: 'white',
      padding: 20,
      borderRadius: 5,
      width: '80%',
    },
    modalText: {
      fontSize: 20,
      textAlign: 'center',
      marginBottom: 10,
    },
    modalButton: {
      backgroundColor: 'green',
      padding: 10,
      borderRadius: 5,
      margin: 5,
    },
    modalButtonText: {
      color: 'white',
      fontWeight: 'bold',
      textAlign: 'center',
    },
    modalButtonCancelar: {
      backgroundColor: 'red',
      padding: 10,
      borderRadius: 5,
      margin: 5,
    },
    modalBackground: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0)',
    },
    modalAviso: {
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#ccc',
        marginBottom: 10,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#ccc',
        marginBottom: 10,
    },
    modalInput: {
        backgroundColor: 'white',
        padding: 5,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: '#ccc',
        margin: 5,
    },
    modalLabel: {
        fontSize: 12,
        marginLeft: 8,
    },
    // ScrollView
    scrollView: {
        backgroundColor: 'white',
    },
    // ComunicacaoModal
    comunicacaoContainer: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    comunicacaoContent: {
        backgroundColor: 'white',
        width: '100%',
        margin: 5,
    },
    comunicacaoText1: {
        fontSize: 15,
        textAlign: 'center',
        margin: 1,
        fontWeight: 'bold',
    },
    comunicacaoText2: {
      fontSize: 15,
      textAlign: 'center',
  },
})